Models/DAL.cs
using MySql.Data.MySqlClient;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Dapper.Contrib.Extensions;
using Dapper;

namespace StackOverflowLab.Models
{
    public class DAL
    {
        public static string CurrentUser = null;
        public static MySqlConnection DB = new MySqlConnection("Server=localhost;Database=foc;Uid=root;Password=abc123");

        //view all questions
        public static List<Questions> AllQuestions()
        {

            return DB.GetAll<Questions>().ToList();
        }

        

        //update or edit question
        public static void EditQuestion(Questions ques)
        {
            ques.username = DAL.CurrentUser;
            DB.Update(ques);
        }

        //view all answers
        public static List<answers> Answers()
        {
            return DB.GetAll<answers>().ToList();
        }

      
        

        //edit or update an answer
        public static void EditAnswer(answers ans)
        {
            ans.username =DAL.CurrentUser;
            DB.Update(ans);
        }

        
        
        // Read the details for an answer by id
        public static answers GetAnswers(int id)
        {
            return DB.Get<answers>(id);
        }

        public static Questions GetQuestions(int id)
        {
            return DB.Get<Questions>(id);
        }

        public static void AddQuestionAndAnswers(Questions ques, answers ans)
        {
            ques.username = DAL.CurrentUser;
            ans.username = DAL.CurrentUser;
            DB.Insert(ques);
            DB.Insert(ans);
        }

       public static void AddAnswer (answers ans)
        {
            ans.username = DAL.CurrentUser;
            DB.Insert(ans);
        }

        public static QuestionsAnswers GetAllForQuestions(int thequesID)
        {
            var keyvalues = new { quesID = thequesID };
            string sql = "select * from answers where questionId=@quesID";
            QuestionsAnswers qa = new QuestionsAnswers();
            qa.ans = DB.Query<answers>(sql, keyvalues).ToList();
            //to get only one question we put in Get.
            qa.ques = DB.Get<Questions>(thequesID);
            return qa;
        }

        //public static List<Questions> SearchProduct(string ques)
        //{

        //    var keyvaluepair = new { search = "%" + ques + "%" };
        //    string sql = "select * from questions where detail like @search or title like @search";
        //    return DB.Query<answers>(sql, keyvaluepair).ToList();
        //}
    }
}

Models/ErrorViewModel.cs
using System;

namespace StackOverflowLab.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Questions.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Dapper.Contrib.Extensions;

namespace StackOverflowLab.Models
{
    [Table("questions")]
    public class Questions
    {
        [Key]
        public int id { get; set; }
        public string username { get; set; }
        public string title { get; set; }
        public string detail { get; set; }
        public  DateTime posted {get; set;}
        public string category { get; set; }
        public string tags { get; set; }
        public int status { get; set; }

    }
}

Models/answers.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Dapper.Contrib.Extensions;
namespace StackOverflowLab.Models
{
    [Table("answers")]
    public class answers
    {
        [Key]
        public int id { get; set; }
        public string username { get; set; }
        public string detail { get; set; }
        public int questionId { get; set; }
        public DateTime posted { get; set; }
        public int upvotes { get; set; }
    }
}

Models/viewmodels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Dapper.Contrib.Extensions;

namespace StackOverflowLab.Models
{
	public class QuestionsAnswers
	{
		public Questions ques { get; set; }
		public List<answers> ans { get; set; }
	}
}

Controllers/AnswersController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using StackOverflowLab.Models;

namespace StackOverflowLab.Controllers
{
    public class AnswersController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ListAnswers(int questID)
        {
            QuestionsAnswers qa = DAL.GetAllForQuestions(questID);
            return View(qa);



        }

        public IActionResult editanswer(int ansid)
        {
            answers emp = DAL.GetAnswers(ansid);
            return View(emp);
        }

        public IActionResult AddAnswer (answers ans)
        {
            DAL.AddAnswer(ans);
            return RedirectToAction("Index");
            
        }

        public IActionResult saveanswer(answers ans)
        {
            DAL.EditAnswer(ans);
            //                /Answers/ListAnswers?questID=1
            return Redirect($"/Answers/ListAnswers?questID={ans.questionId}");
        }
    }
}

Controllers/FOCDevController.cs
using Microsoft.AspNetCore.Mvc;
using StackOverflowLab.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StackOverflowLab.Controllers
{
    public class FOCDevController : Controller
    {
		public IActionResult Index()
		{
			List<Questions> ques = DAL.AllQuestions();
			return View(ques);
		}

		public IActionResult Questions (string ques)
        {
			return Content(ques);
        }
		public IActionResult editquestion (int quesid)
		{
			Questions ques = DAL.GetQuestions(quesid);
			return View(ques);
		}

		public IActionResult savequestion(Questions ques)
		{
			DAL.EditQuestion(ques);
			
			return Redirect($"/focdev/index?quesID={ques.id}");
		}



	}
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using StackOverflowLab.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace StackOverflowLab.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Answers/AddAnswer.cshtml
@{
    ViewData["Title"] = "AddAnswer";
}

<h1>Add Answer</h1>

<form method="post" action="/focdev">
    Username: <input type="text" name="username" /> <br />
    Detail: <input type="text" name="detail" /> <br />
    Question ID: <input type="text" name="questionID" /> <br />
    Date Posted: <input type="date" name=" posted" /><br />

</form>

Views/Answers/ListAnswers.cshtml
@model QuestionsAnswers
@{
    ViewData["Title"] = "ListAnswers";
}

<h1>List Answers</h1>

@Model.ques.detail <br />
@foreach (answers ans in Model.ans)
            {
                @ans.detail @ans.posted <a href="/answers/editanswer?ansid=@ans.id">Edit</a>
            }

Views/Answers/editanswer.cshtml
@model answers
@{
    ViewData["Title"] = "editanswer";
}

<h1>edit answer</h1>
<form method="post" action="/answers/saveanswer">
    <input type="hidden" name="id" value="@Model.id" />
    
    Detail: <input type="text" name="detail" value="@Model.detail" /><br />
    Question ID: <input type="text" readonly="readonly" name="questionId" value="@Model.questionId" /><br />
    <input type="submit" value="Save" />
</form>

Views/FOCDev/Index.cshtml
@model List<Questions>
@{
    ViewData["Title"] = "Index";
}

<h1>List of Questions</h1>



<table class="table">
    <thead>
        <tr>
            <th> id </th>
            <th>username</th>
            <th>title</th>
            <th>detail</th>
            <th>posted</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Questions ques in Model)
        {
        <tr>
            <td>@ques.id</td>
            <td>@ques.username</td>
            <td>@ques.title</td>
            <td>@ques.detail</td>
            <td>@ques.posted</td>

            <td>
                <a asp-action="Edit" asp-route-quesid="@ques.id" class="btn btn-primary">Edit Question </a>
                <a asp-action="Edit" asp-route-quesid="@ques.id" class="btn btn-secondary">Edit Answer</a>
                <a asp-controller="Answers" asp-action="ListAnswers" asp-route-questID="@ques.id" class="btn btn-primary">View Answers</a>
            </td>
        </tr>
        }
    </tbody>
</table>   
<a asp-action="NewQuestion" class="btn btn-primary">New Question</a>

Views/FOCDev/editquestion.cshtml
@model Questions
@{
    ViewData["Title"] = "editquestion";
}

<h1>edit question</h1>

<form method="post" action="/focdev/savequestion">
    <input type="hidden" name="id" value="@Model.id" />

    Detail: <input type="text" name="detail" value="@Model.detail" /><br />
    
    <input type="submit" value="Save" />
</form>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <h2 style=" text-align:center; color: aqua;">This app will allow FOC developers to add, edit or delete questions and answers!</h2>
   </div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StackOverflowLab</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">StackOverflowLab</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - StackOverflowLab - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>